import type { FaqItem } from "@/lib/content/types";

const faqs: FaqItem[] = [
  {
    id: "what-is-edible-cutlery",
    question: "What is edible cutlery?",
    answer: "Edible cutlery is tableware made from baked, food-grade ingredients such as grain flour and natural binders. It is designed to be used like ordinary cutlery and then eaten or discarded, in which case it breaks down much faster than plastic.",
    category: "Basics & Definitions",
  },
  {
    id: "is-edible-cutlery-real",
    question: "Is edible cutlery a real product or just a marketing gimmick?",
    answer: "It is a real manufactured food product used in hospitality, foodservice, aviation, and events. It is not just a novelty item; it is a functional product that is evaluated and ordered at commercial scale.",
    category: "Basics & Definitions",
  },
  {
    id: "edible-vs-biodegradable",
    question: "What is the difference between edible cutlery and biodegradable cutlery?",
    answer: "Edible cutlery is safe to eat, while biodegradable cutlery is simply designed to break down over time. A product can be biodegradable without being food-safe to eat, but edible cutlery is specifically made to be consumed or naturally disposed of.",
    category: "Basics & Definitions",
  },
  {
    id: "edible-vs-compostable",
    question: "What is the difference between edible and compostable cutlery?",
    answer: "Compostable cutlery breaks down under specific composting conditions, while edible cutlery is made to be eaten or discarded as food-based waste. In practice, edible cutlery can meet both goals, but the two categories are not identical.",
    category: "Basics & Definitions",
  },
  {
    id: "does-edible-cutlery-contain-plastic",
    question: "Does edible cutlery contain any plastic?",
    answer: "No. Genuine edible cutlery is made from food-grade ingredients such as grain flour, water, and natural binders, with no plastic resin or synthetic coating.",
    category: "Basics & Definitions",
  },
  {
    id: "who-uses-edible-cutlery",
    question: "Who typically uses edible cutlery?",
    answer: "Hotels, restaurants, cafes, airlines, railways, caterers, corporate cafeterias, and delivery operations are the most common users because they generate high volumes of single-use cutlery and want a lower-waste option.",
    category: "Basics & Definitions",
  },
  {
    id: "is-edible-cutlery-the-same-everywhere",
    question: "Is edible cutlery the same across every brand that sells it?",
    answer: "No. Formulation, thickness, flavor, and manufacturing quality vary between brands, so buyers should evaluate the real product specifications rather than assume every edible cutlery product is identical.",
    category: "Basics & Definitions",
  },
  {
    id: "what-is-edible-cutlery-made-from",
    question: "What is edible cutlery made from?",
    answer: "Most edible cutlery is made from baked grain flour such as millet, sorghum, wheat, or rice, combined with water and a natural binder and then shaped and baked until firm.",
    category: "Ingredients & Manufacturing",
  },
  {
    id: "how-is-edible-cutlery-manufactured",
    question: "How is edible cutlery manufactured?",
    answer: "The manufacturing process usually involves mixing a flour-based dough, pressing it into cutlery-shaped molds, baking it until it is rigid, cooling and checking each batch, and then packaging it in moisture-resistant, food-safe material.",
    category: "Ingredients & Manufacturing",
  },
  {
    id: "why-is-baking-time-important",
    question: "Why is baking time important in edible cutlery production?",
    answer: "Baking time determines whether the product is crisp, rigid, and shelf-stable. Under-baked cutlery can feel soft, bend easily, and fail earlier in real service conditions.",
    category: "Ingredients & Manufacturing",
  },
  {
    id: "does-edible-cutlery-use-preservatives",
    question: "Does edible cutlery use artificial preservatives?",
    answer: "It depends on the manufacturer and formulation, but the product is generally designed to be a shelf-stable food product rather than a chemically preserved novelty item.",
    category: "Ingredients & Manufacturing",
  },
  {
    id: "can-edible-cutlery-be-flavored",
    question: "Can edible cutlery be flavored?",
    answer: "Yes. Some product lines offer mild sweet or savory flavors, although many brands keep the flavor neutral so the utensil does not compete with the food it is served with.",
    category: "Ingredients & Manufacturing",
  },
  {
    id: "is-edible-cutlery-handmade-or-machine-made",
    question: "Is edible cutlery handmade or machine-manufactured?",
    answer: "At commercial scale, it is usually machine-molded and industrially baked so it can be produced consistently and meet the performance standards expected by foodservice buyers.",
    category: "Ingredients & Manufacturing",
  },
  {
    id: "is-edible-cutlery-safe-to-eat",
    question: "Is edible cutlery actually safe to eat?",
    answer: "Yes. Properly made edible cutlery is manufactured with food-grade ingredients and sold as a food product, so it is safe to consume when handled and stored correctly.",
    category: "Safety, Allergens & Food Handling",
  },
  {
    id: "is-edible-cutlery-gluten-free",
    question: "Is edible cutlery gluten-free?",
    answer: "It depends on the base flour. Millet- and sorghum-based products are naturally gluten-free, while wheat-based products are not.",
    category: "Safety, Allergens & Food Handling",
  },
  {
    id: "can-vegetarians-and-vegans-eat-it",
    question: "Can vegetarians and vegans eat edible cutlery?",
    answer: "Most edible cutlery is plant-based and suitable for vegetarian and vegan diets, but buyers should still check the specific ingredient list because formulations vary by product line.",
    category: "Safety, Allergens & Food Handling",
  },
  {
    id: "does-edible-cutlery-contain-common-allergens",
    question: "Does edible cutlery contain common allergens?",
    answer: "Yes, it can. Wheat-based products contain gluten, and other ingredients may trigger additional allergen concerns depending on the formulation and manufacturer.",
    category: "Safety, Allergens & Food Handling",
  },
  {
    id: "is-it-safe-for-hospitals",
    question: "Is edible cutlery safe for hospital or healthcare settings?",
    answer: "It can be appropriate for staff and visitor cafeteria settings when handled like any other food product, but patient meal tray use should be reviewed with clinical and dietary teams because of allergy and texture considerations.",
    category: "Safety, Allergens & Food Handling",
  },
  {
    id: "what-if-someone-has-an-allergy",
    question: "What happens if someone with a food allergy accidentally eats edible cutlery?",
    answer: "The same allergy-response principles apply as with any other food product. Clear labeling, ingredient transparency, and staff awareness are essential so allergic guests are protected.",
    category: "Safety, Allergens & Food Handling",
  },
  {
    id: "can-edible-cutlery-handle-hot-soup",
    question: "Can edible cutlery handle hot soup?",
    answer: "Yes, for the normal duration of a meal. Like any baked grain-based product, it will soften if it sits in hot liquid for too long or is left submerged beyond typical eating time.",
    category: "Performance & Durability",
  },
  {
    id: "is-it-strong-enough-for-ice-cream",
    question: "Is edible cutlery strong enough for ice cream?",
    answer: "Yes. Cold, low-moisture desserts are one of the most reliable use cases for edible spoons because the product stays firm and performs as intended for a standard serving.",
    category: "Performance & Durability",
  },
  {
    id: "will-edible-cutlery-fall-apart-in-liquid",
    question: "Will edible cutlery fall apart in any liquid?",
    answer: "Not in the normal sense of a typical meal. It is built to perform for a standard eating duration, but it is not intended to sit indefinitely in liquid.",
    category: "Performance & Durability",
  },
  {
    id: "can-edible-straws-handle-full-drinks",
    question: "Can edible straws handle a full drink without softening?",
    answer: "They perform best when the drink is consumed at a normal pace. Because straws remain in contact with liquid for longer than a spoon or fork, they are more sensitive to dwell time and drink temperature.",
    category: "Performance & Durability",
  },
  {
    id: "does-it-work-for-buffet-lines",
    question: "Does edible cutlery work for buffet or self-service lines?",
    answer: "It can, but it should be chosen carefully for the service environment. Thicker formats and faster turnover reduce the risk of softening when items sit in service stations or buffet dishes.",
    category: "Performance & Durability",
  },
  {
    id: "what-does-it-feel-like-when-you-bite-it",
    question: "What does edible cutlery feel like when you bite it?",
    answer: "It is usually firm and slightly dense, more like a crisp cracker or biscuit than something soft or chewy. That texture is part of what makes it practical for everyday use.",
    category: "Performance & Durability",
  },
  {
    id: "can-it-cut-solid-food",
    question: "Can edible cutlery cut through solid food like a knife?",
    answer: "No. Edible cutlery is designed for scooping, poking, and light piercing rather than cutting through dense or tough foods.",
    category: "Performance & Durability",
  },
  {
    id: "how-long-does-edible-cutlery-last-in-storage",
    question: "How long does edible cutlery last in storage?",
    answer: "Shelf life varies by formulation and packaging, but it should be treated as a food product with a defined shelf life. Cool, dry storage helps it perform as intended for longer.",
    category: "Storage & Shelf Life",
  },
  {
    id: "how-should-it-be-stored",
    question: "How should edible cutlery be stored?",
    answer: "It should be kept in a cool, dry place in its original sealed packaging, following standard food-product stock rotation practices rather than the loose storage approach used for plastic cutlery.",
    category: "Storage & Shelf Life",
  },
  {
    id: "what-is-the-biggest-threat-to-shelf-life",
    question: "What is the biggest threat to edible cutlery's shelf life?",
    answer: "Humidity is usually the main issue. Moisture can soften the product and degrade packaging integrity, which is why dry storage matters so much.",
    category: "Storage & Shelf Life",
  },
  {
    id: "can-it-be-stored-near-dishwashing-station",
    question: "Can edible cutlery be stored near a dishwashing station or walk-in cooler?",
    answer: "It is best avoided in damp or high-condensation environments because moisture and humidity can shorten shelf life even if the packaging remains sealed.",
    category: "Storage & Shelf Life",
  },
  {
    id: "does-it-expire-like-other-food-products",
    question: "Does edible cutlery expire like other food products?",
    answer: "Yes. It has a defined shelf life and should not be used past its listed date, just as you would not use expired packaged food.",
    category: "Storage & Shelf Life",
  },
  {
    id: "is-it-better-for-the-environment-than-plastic",
    question: "Is edible cutlery actually better for the environment than plastic?",
    answer: "Yes, in terms of end-of-life waste. It is either eaten or breaks down much faster than plastic, which can persist in the environment for a very long time.",
    category: "Sustainability & Environmental Impact",
  },
  {
    id: "what-happens-if-it-is-thrown-away",
    question: "What happens to edible cutlery if it is thrown away instead of eaten?",
    answer: "It breaks down naturally within days because it is made from food-based ingredients and can generally be treated as compostable waste rather than long-lived plastic waste.",
    category: "Sustainability & Environmental Impact",
  },
  {
    id: "does-growing-the-grain-have-an-impact",
    question: "Does growing the grain for edible cutlery have an environmental impact?",
    answer: "Yes. Like any agricultural product, grain production has a footprint, so edible cutlery is not zero-impact. The comparative advantage is mainly the much shorter waste lifecycle.",
    category: "Sustainability & Environmental Impact",
  },
  {
    id: "can-it-help-meet-esg-goals",
    question: "Can edible cutlery help a business meet sustainability or ESG goals?",
    answer: "It can, especially for companies tracking single-use plastic reduction and waste diversion. It is often used as a visible and practical part of a broader sustainability program.",
    category: "Sustainability & Environmental Impact",
  },
  {
    id: "is-it-recyclable",
    question: "Is edible cutlery recyclable?",
    answer: "Recycling is not the main framework for edible cutlery. It is intended to be eaten or to biodegrade naturally rather than processed through conventional recycling infrastructure.",
    category: "Sustainability & Environmental Impact",
  },
  {
    id: "does-it-break-down-on-international-flights",
    question: "Does edible cutlery break down the same way on an international flight?",
    answer: "Not always. Some countries regulate international catering waste under biosecurity rules that require special disposal treatment, so airlines should treat the plastic-displacement benefit as the primary sustainability advantage.",
    category: "Sustainability & Environmental Impact",
  },
  {
    id: "is-it-better-than-plastic",
    question: "Is edible cutlery better than plastic cutlery?",
    answer: "It depends on the priority. Edible cutlery is better for end-of-life waste, while plastic cutlery often wins on low unit cost and maximum durability.",
    category: "Comparisons with Other Cutlery",
  },
  {
    id: "is-it-better-than-wooden-cutlery",
    question: "Is edible cutlery better than wooden cutlery?",
    answer: "Wooden cutlery often performs better in long liquid contact because wood does not soften the same way a baked grain product does, but edible cutlery offers the additional benefit of being consumable if eaten.",
    category: "Comparisons with Other Cutlery",
  },
  {
    id: "is-it-better-than-bamboo-cutlery",
    question: "Is edible cutlery better than bamboo cutlery?",
    answer: "That depends on whether the bamboo product is meant to be reused or disposed of after a single use. The two solutions are often chosen for different operational reasons.",
    category: "Comparisons with Other Cutlery",
  },
  {
    id: "is-it-better-than-paper-cutlery",
    question: "Is edible cutlery better than paper cutlery?",
    answer: "In general, yes for liquid-heavy use, because paper cutlery tends to soften quickly while edible cutlery is more robust for ordinary meal durations.",
    category: "Comparisons with Other Cutlery",
  },
  {
    id: "should-a-restaurant-use-edible-or-steel",
    question: "Should a restaurant use edible cutlery or reusable steel cutlery?",
    answer: "Many operations use steel for dine-in service where washing infrastructure exists and edible cutlery for takeout, delivery, or single-use moments where disposable service is more practical.",
    category: "Comparisons with Other Cutlery",
  },
  {
    id: "which-plastic-free-option-is-cheapest",
    question: "Which plastic-free cutlery option is cheapest?",
    answer: "Paper cutlery is typically the lowest-cost plastic-free option, while edible cutlery is usually more expensive per unit because it is manufactured as a food product.",
    category: "Comparisons with Other Cutlery",
  },
  {
    id: "is-there-a-minimum-order-quantity",
    question: "Is there a minimum order quantity for edible cutlery?",
    answer: "Yes. Business orders usually have a minimum order quantity that varies by product line, volume, and customization requirements.",
    category: "Ordering & Business",
  },
  {
    id: "can-it-be-custom-branded",
    question: "Can edible cutlery be custom-branded for a business?",
    answer: "Yes. Many businesses request private labeling, custom shapes, or co-branded packaging for hospitality, events, and delivery programs.",
    category: "Ordering & Business",
  },
  {
    id: "how-far-in-advance-should-a-business-order",
    question: "How far in advance should a business order edible cutlery for a large event?",
    answer: "As early as possible, the same way a business would plan other major catering or event supplies. Lead times depend on volume, customization, and shipping requirements.",
    category: "Ordering & Business",
  },
  {
    id: "does-it-cost-more-than-plastic",
    question: "Does edible cutlery cost more than plastic cutlery to switch to?",
    answer: "Usually yes on a per-unit basis, because it is a manufactured food product rather than a low-cost molded plastic item. Some businesses offset that cost through reduced waste handling and stronger guest-facing sustainability messaging.",
    category: "Ordering & Business",
  },
  {
    id: "can-a-small-cafe-order-it",
    question: "Can a small cafe or restaurant order edible cutlery, or is it only for large operations?",
    answer: "Both can order it. Smaller businesses may buy smaller volumes, while larger operations usually benefit more from volume pricing and broader rollout plans.",
    category: "Ordering & Business",
  },
  {
    id: "what-documentation-should-a-business-request",
    question: "What documentation should a business request before placing a bulk order?",
    answer: "A business should request ingredient information, allergen details, shelf-life specifications, food safety documentation, and any relevant packaging or export information before placing a bulk order.",
    category: "Ordering & Business",
  },
  {
    id: "where-can-a-business-get-a-quote",
    question: "Where can a business get a quote for edible cutlery?",
    answer: "Businesses can request a sample and quote directly from Snacklery to review pricing, product options, volume requirements, and customization needs for their operation.",
    category: "Ordering & Business",
  },
  {
    id: "can-edible-cutlery-be-used-in-airlines",
    question: "Can edible cutlery be used in airline meal service?",
    answer: "Yes, although weight, extended pre-service storage, and international waste-disposal rules are meaningful aviation-specific considerations. Airlines should review the operational fit carefully before a rollout.",
    category: "Industry-Specific Questions",
  },
  {
    id: "is-it-suitable-for-hospital-patient-trays",
    question: "Is edible cutlery suitable for hospital patient meal trays?",
    answer: "Not as a default recommendation. Patient populations can have allergen, dietary, or swallowing-safety considerations that require clinical review before introducing a new food item to patient trays.",
    category: "Industry-Specific Questions",
  },
  {
    id: "can-hotels-use-it-in-room-service",
    question: "Can hotels use edible cutlery in room service?",
    answer: "Yes. Room service is one of the most practical pilot points for hotels because usage volume is often lower than in a buffet while guest visibility is high.",
    category: "Industry-Specific Questions",
  },
  {
    id: "is-it-good-for-wedding-catering",
    question: "Is edible cutlery a good fit for wedding catering?",
    answer: "Yes. Plated wedding courses are a strong fit because presentation is already important and edible cutlery adds a memorable and talkable detail for guests.",
    category: "Industry-Specific Questions",
  },
  {
    id: "can-food-delivery-apps-include-it",
    question: "Can food delivery apps include edible cutlery with orders?",
    answer: "Yes. Edible sporks are often the strongest default for delivery because mixed meals and on-the-go eating are common in that channel.",
    category: "Industry-Specific Questions",
  },
  {
    id: "is-it-suitable-for-railway-catering",
    question: "Is edible cutlery suitable for railway catering?",
    answer: "Yes, with attention to storage timelines and waste-handling practices that are specific to rail operations. The operational fit should be reviewed carefully before rollout.",
    category: "Industry-Specific Questions",
  },
  {
    id: "can-corporate-cafeterias-use-it-at-buffets",
    question: "Can corporate cafeterias use edible cutlery at buffet stations?",
    answer: "Yes. Thicker, soup-friendly formats tend to perform more predictably in self-service buffet settings because they hold up better with longer dwell times.",
    category: "Industry-Specific Questions",
  },
  {
    id: "is-it-a-good-fit-for-fast-food",
    question: "Is edible cutlery a good fit for fast food or quick-service restaurants?",
    answer: "It can be, but cost sensitivity is a bigger factor here than in premium hospitality settings. The value case should be weighed carefully against the higher per-unit cost relative to plastic.",
    category: "Industry-Specific Questions",
  },
  {
    id: "can-cafes-replace-all-disposable-items",
    question: "Can cafes replace all disposable items with edible cutlery?",
    answer: "Not entirely. Edible cutlery covers utensils well, but cups, lids, and napkins still require separate sustainable alternatives.",
    category: "Industry-Specific Questions",
  },
  {
    id: "is-it-practical-for-food-trucks",
    question: "Is edible cutlery practical for food trucks or street vendors?",
    answer: "It can be, though smaller mobile operations should weigh order volume, minimum order quantities, and storage constraints carefully before switching.",
    category: "Industry-Specific Questions",
  },
  {
    id: "difference-edible-spoon-vs-spork",
    question: "What is the difference between an edible spoon and an edible spork?",
    answer: "A spoon is optimized for scooping, while a spork combines a shallow bowl with fork-like tines so it can handle both scooping and piercing in mixed-texture meals.",
    category: "Product Formats",
  },
  {
    id: "are-edible-knives-available",
    question: "Are edible knives available?",
    answer: "Edible cutlery in its current mainstream form generally covers spoons, forks or sporks, stirrers, and straws rather than a dedicated knife format for cutting dense foods.",
    category: "Product Formats",
  },
  {
    id: "do-edible-stirrers-come-in-different-lengths",
    question: "Do edible stirrers come in different lengths?",
    answer: "Yes. Formats commonly range from short espresso-style stirrers to standard coffee and tea sizes and longer cocktail-length styles.",
    category: "Product Formats",
  },
  {
    id: "what-sizes-do-edible-spoons-come-in",
    question: "What sizes do edible spoons come in?",
    answer: "Common formats include soup spoons, dessert spoons, and mini spoons for beverages, each designed for a different type of eating experience.",
    category: "Product Formats",
  },
  {
    id: "are-bent-or-flexible-straws-available",
    question: "Are bent or flexible edible straws available?",
    answer: "That depends on the manufacturer and product line. Some brands offer alternative straw geometries, while others focus on straight, standard formats.",
    category: "Product Formats",
  },
  {
    id: "can-edible-sporks-handle-noodles",
    question: "Can edible sporks handle noodle dishes well?",
    answer: "Yes, reasonably well. Noodles are usually scooping-dominant with some piercing required, which makes the spork a practical all-rounder for many mixed dishes.",
    category: "Product Formats",
  },
  {
    id: "is-there-a-combined-cutlery-set",
    question: "Is there a combined edible cutlery set with spoon, fork, and stirrer together?",
    answer: "That depends on the supplier. Some suppliers sell individual formats, while others offer bundled or multi-format sets for hospitality or event use.",
    category: "Product Formats",
  },
  {
    id: "do-edible-spoons-have-different-bowl-depths",
    question: "Do edible spoons have different bowl depths for different foods?",
    answer: "Yes. Soup spoons use a deeper bowl for liquid-heavy use, while dessert spoons are shallower and suited to lighter, lower-moisture foods.",
    category: "Product Formats",
  },
  {
    id: "what-is-the-standard-length-of-an-edible-stirrer",
    question: "What is the standard length of an edible stirrer?",
    answer: "The length varies by format, with short, standard, and long cocktail-style sizes all used depending on the beverage and service environment.",
    category: "Product Formats",
  },
  {
    id: "can-custom-designs-beyond-standard-shapes",
    question: "Can edible cutlery be shaped into custom designs beyond standard spoon or fork shapes?",
    answer: "Custom shaping is possible in some cases, especially for premium or branded orders, but it depends on the manufacturer’s mold capabilities and the product line.",
    category: "Product Formats",
  },
  {
    id: "how-many-calories-are-in-a-piece",
    question: "How many calories are in a piece of edible cutlery?",
    answer: "This depends on the formulation and size, so it should be treated like any other packaged food item with nutrition details provided by the manufacturer.",
    category: "Health & Dietary Questions",
  },
  {
    id: "is-it-suitable-for-diabetics",
    question: "Is edible cutlery suitable for diabetics?",
    answer: "That depends on the specific ingredients and any added sugars in a given formulation. Individuals managing blood sugar should review nutrition details directly with a healthcare provider.",
    category: "Health & Dietary Questions",
  },
  {
    id: "can-children-safely-eat-it",
    question: "Can children safely eat edible cutlery?",
    answer: "Yes, when it is manufactured to food safety standards, but as with any firm snack food, normal food-safety judgment around choking risk for very young children should apply.",
    category: "Health & Dietary Questions",
  },
  {
    id: "is-it-keto-friendly",
    question: "Is edible cutlery keto-friendly?",
    answer: "Most edible cutlery is grain-based and therefore contains carbohydrates, so it is generally not aligned with a strict ketogenic diet.",
    category: "Health & Dietary Questions",
  },
  {
    id: "does-it-contain-added-sugar",
    question: "Does edible cutlery contain added sugar?",
    answer: "That depends on the formulation. Neutral products usually do not, while flavored variants may contain some sugar or sweetener.",
    category: "Health & Dietary Questions",
  },
  {
    id: "is-it-safe-for-celiac-disease",
    question: "Is edible cutlery safe for people with celiac disease?",
    answer: "Only if it is made from certified gluten-free ingredients and produced without cross-contamination risk. People with celiac disease should verify certification directly rather than assume based on the base flour.",
    category: "Health & Dietary Questions",
  },
  {
    id: "do-single-use-plastic-bans-affect-it",
    question: "Do single-use plastic bans affect edible cutlery differently than plastic cutlery?",
    answer: "Generally yes. Because edible cutlery is a food-based product rather than a plastic item, it often falls outside the specific rules aimed at plastic tableware, although the exact treatment depends on jurisdiction.",
    category: "Environmental & Regulatory Questions",
  },
  {
    id: "is-it-compliant-with-eu-plastics-directive",
    question: "Is edible cutlery compliant with regulations like the EU's single-use plastics directive?",
    answer: "As a non-plastic, food-based product, edible cutlery is generally outside the scope of regulations targeting single-use plastic items specifically, but classification can vary by market.",
    category: "Environmental & Regulatory Questions",
  },
  {
    id: "can-it-help-avoid-plastic-taxes",
    question: "Can using edible cutlery help a business avoid plastic taxes or levies?",
    answer: "In some jurisdictions, yes. Since it is not a plastic item, it may fall outside a plastic-specific charge, but businesses should confirm their local rules rather than assume automatic exemption.",
    category: "Environmental & Regulatory Questions",
  },
  {
    id: "are-there-food-safety-regulations",
    question: "Are there specific food safety regulations that apply to edible cutlery?",
    answer: "Yes. Because it is manufactured to be eaten, edible cutlery is subject to food safety and manufacturing rules in the same general way packaged snack foods are.",
    category: "Environmental & Regulatory Questions",
  },
  {
    id: "does-it-count-toward-epr-reduction-targets",
    question: "Does using edible cutlery count toward Extended Producer Responsibility plastic-reduction targets?",
    answer: "It may, depending on how the local EPR framework is defined. The answer depends on the accounting rules in each jurisdiction rather than a universal rule.",
    category: "Environmental & Regulatory Questions",
  },
  {
    id: "is-it-classified-as-packaging-or-food",
    question: "Is edible cutlery classified as packaging or as a food product for regulatory purposes?",
    answer: "It is generally treated as a food product, which is a meaningfully different regulatory category from packaging or tableware and affects labeling and food-safety requirements.",
    category: "Environmental & Regulatory Questions",
  },
  {
    id: "why-did-it-arrive-broken-or-cracked",
    question: "Why did my edible cutlery arrive broken or cracked?",
    answer: "This is often a shipping or handling issue, though inconsistent baking can also produce more brittle pieces. Frequent breakage across a shipment should be raised with the supplier as a quality concern.",
    category: "Quality & Troubleshooting",
  },
  {
    id: "what-causes-stale-taste",
    question: "What causes edible cutlery to taste stale?",
    answer: "Staleness usually signals the product is near or past its shelf life, or that it has been exposed to air or humidity because of damaged or improperly resealed packaging.",
    category: "Quality & Troubleshooting",
  },
  {
    id: "how-can-i-tell-if-it-has-gone-bad",
    question: "How can I tell if edible cutlery has gone bad?",
    answer: "Signs include a stale or off smell, a noticeably softened or gummy texture, or visible mold. Those are the same quality indicators you would look for in any baked food product past its shelf life.",
    category: "Quality & Troubleshooting",
  },
  {
    id: "why-does-it-feel-too-hard-to-bite",
    question: "Why does edible cutlery sometimes feel too hard to bite?",
    answer: "That can happen with over-baking, or it may simply reflect the intended firm cracker-like texture. If it feels unusually hard compared with previous orders, it is worth raising with the supplier.",
    category: "Quality & Troubleshooting",
  },
  {
    id: "what-if-it-softens-too-quickly",
    question: "What should I do if edible cutlery softens too quickly during service?",
    answer: "That usually signals a format mismatch rather than a product defect. Check the use-case guidance for the right product format rather than assuming the same cutlery will perform equally well in every service environment.",
    category: "Quality & Troubleshooting",
  },
  {
    id: "is-color-variation-between-batches-normal",
    question: "Is slight color variation between batches of edible cutlery normal?",
    answer: "Yes, to a degree. Natural grain flour can vary slightly in color from batch to batch, just like other baked foods. Significant or inconsistent variation should be discussed with the supplier.",
    category: "Quality & Troubleshooting",
  },
  {
    id: "can-edible-cutlery-be-exported",
    question: "Can edible cutlery be exported internationally?",
    answer: "Generally yes, although it is treated as a food product and is therefore subject to destination-country import regulations and food safety requirements.",
    category: "Export & International Shipping",
  },
  {
    id: "does-it-require-special-customs-documentation",
    question: "Does edible cutlery require special customs documentation?",
    answer: "As a food product, it will usually require food-specific import documentation beyond what a standard plastic tableware shipment would need.",
    category: "Export & International Shipping",
  },
  {
    id: "how-does-humidity-affect-shipping",
    question: "How does humidity in tropical climates affect edible cutlery during shipping?",
    answer: "Humidity is the biggest threat to both shelf life and structural integrity, so shipments to high-humidity regions need strong moisture-resistant packaging and fast turnover.",
    category: "Export & International Shipping",
  },
  {
    id: "can-it-survive-sea-freight",
    question: "Can edible cutlery survive sea freight shipping without spoiling?",
    answer: "It depends on transit duration, packaging quality, and container humidity control. Sea freight generally carries more risk than air freight for a moisture-sensitive food product.",
    category: "Export & International Shipping",
  },
  {
    id: "are-there-country-import-restrictions",
    question: "Are there countries with import restrictions on edible cutlery?",
    answer: "Possibly. Since it is classified as a food product, some countries may impose additional inspection or import requirements that would not apply to non-food tableware.",
    category: "Export & International Shipping",
  },
  {
    id: "does-snacklery-ship-internationally",
    question: "Does Snacklery ship edible cutlery internationally?",
    answer: "That depends on current shipping capability and the destination market. Businesses should confirm current export capability directly before planning an international order.",
    category: "Export & International Shipping",
  },
  {
    id: "can-i-request-a-free-sample",
    question: "Can I request a free sample of edible cutlery?",
    answer: "Businesses can usually request a sample to evaluate the product before placing a larger order, although sample availability and any associated cost depend on the supplier’s current policy.",
    category: "Samples & Pilot Programs",
  },
  {
    id: "how-do-i-start-a-pilot-program",
    question: "How do I start a pilot program with edible cutlery at my business?",
    answer: "The most effective pilots start with one outlet, service point, or menu category so the team can test performance in a realistic but contained use case.",
    category: "Samples & Pilot Programs",
  },
  {
    id: "what-is-the-best-way-to-test-it",
    question: "What is the best way to test edible cutlery before committing to a bulk order?",
    answer: "A sample and a targeted pilot against the highest-priority use case gives the clearest result, because main performance differences usually come from format-to-use-case fit rather than product quality alone.",
    category: "Samples & Pilot Programs",
  },
  {
    id: "how-long-should-a-pilot-run",
    question: "How long should a pilot program typically run before deciding on a full rollout?",
    answer: "It should run long enough to capture a representative sample of real usage, staff feedback, and guest experience rather than a fixed universal timeframe.",
    category: "Samples & Pilot Programs",
  },
  {
    id: "can-snacklery-help-design-a-rollout-plan",
    question: "Can Snacklery help design a rollout plan for my business?",
    answer: "Yes. Businesses can discuss their operation, expected volume, and use cases with the Snacklery team to shape a practical rollout approach before ordering at scale.",
    category: "Samples & Pilot Programs",
  },
  {
    id: "who-do-i-contact-to-get-started",
    question: "Who do I contact to get started with edible cutlery for my business?",
    answer: "Businesses should contact Snacklery directly with information about their operation, expected volume, and intended use cases to receive format guidance and pricing.",
    category: "Samples & Pilot Programs",
  },
];

export default faqs;
